version: '3.8'

services:
  # Serviço da aplicação Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=paynet_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
    networks:
      - laravel_network
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "63797:6379"
    networks:
      - laravel_network

  # Serviço do Nginx
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel_network
    depends_on:
      - app

  # Serviço do PostgreSQL
  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: paynet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "54327:5432"
    networks:
      - laravel_network

# Configuração de volumes e rede
volumes:
  postgres_data:

networks:
  laravel_network:
    driver: bridge